GET http://localhost:7071/api/httpget HTTP/1.1

###

POST http://localhost:7071/api/httppostbody HTTP/1.1
content-type: application/json

{
    "person": 
    {
        "name": "Awesome Developer",
        "age": 25 
    }
}
